USE [master]
GO

/****** Object:  Database [formula]    Script Date: 2021-01-19 16:45:30 ******/
CREATE DATABASE [formula]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'formula', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\formula.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'formula_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\formula_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [formula].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [formula] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [formula] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [formula] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [formula] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [formula] SET ARITHABORT OFF 
GO

ALTER DATABASE [formula] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [formula] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [formula] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [formula] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [formula] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [formula] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [formula] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [formula] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [formula] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [formula] SET  ENABLE_BROKER 
GO

ALTER DATABASE [formula] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [formula] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [formula] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [formula] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [formula] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [formula] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [formula] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [formula] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [formula] SET  MULTI_USER 
GO

ALTER DATABASE [formula] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [formula] SET DB_CHAINING OFF 
GO

ALTER DATABASE [formula] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [formula] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [formula] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [formula] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [formula] SET QUERY_STORE = OFF
GO

ALTER DATABASE [formula] SET  READ_WRITE 
GO

